// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBzRXwU9lIXUzTonMUWZxSEU62seSfpfg',
    appId: '1:77195099650:web:cecfc74a7a697cd157b11b',
    messagingSenderId: '77195099650',
    projectId: 'atik-ayristirma-app',
    authDomain: 'atik-ayristirma-app.firebaseapp.com',
    storageBucket: 'atik-ayristirma-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHLHFq4T2mJBkdK9XWwq0CtlcowDkEXUo',
    appId: '1:77195099650:android:5b46ca6912abc1a457b11b',
    messagingSenderId: '77195099650',
    projectId: 'atik-ayristirma-app',
    storageBucket: 'atik-ayristirma-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7lyOnmPZgZIZz_uZ1Nc9LsNIIr9gZgn4',
    appId: '1:77195099650:ios:40b4e9d6ccc24d8b57b11b',
    messagingSenderId: '77195099650',
    projectId: 'atik-ayristirma-app',
    storageBucket: 'atik-ayristirma-app.firebasestorage.app',
    iosBundleId: 'com.example.atikAyristirmaProjesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7lyOnmPZgZIZz_uZ1Nc9LsNIIr9gZgn4',
    appId: '1:77195099650:ios:40b4e9d6ccc24d8b57b11b',
    messagingSenderId: '77195099650',
    projectId: 'atik-ayristirma-app',
    storageBucket: 'atik-ayristirma-app.firebasestorage.app',
    iosBundleId: 'com.example.atikAyristirmaProjesi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBzRXwU9lIXUzTonMUWZxSEU62seSfpfg',
    appId: '1:77195099650:web:1646a2076e9ac7c857b11b',
    messagingSenderId: '77195099650',
    projectId: 'atik-ayristirma-app',
    authDomain: 'atik-ayristirma-app.firebaseapp.com',
    storageBucket: 'atik-ayristirma-app.firebasestorage.app',
  );
}
